// tic-tac-toe.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>
#include <conio.h>
#include <string>
#include <cstdlib>
#include <cctype>
#include <random>
#include <chrono>

#include "game_functions.h"

// using directives
using std::cout;
using std::cin;
using std::cerr;
using std::string;



// global variables
const int DIMENSION_SIZE = 3;
char gameBoard[DIMENSION_SIZE][DIMENSION_SIZE] = { {'1','2','3'},{'4','5','6'},{'7','8','9'} };
char marker = 'X';
const char marker1 = 'X';
const char marker2 = 'O';
int row;
int col;
int turn_counter = 0;
int gameMode = 1;
bool unsuccessfulChoice = false;
string player1 = "Player1";
string player2 = "Player2";


// random numbers generator from <chrono> with seed generated by <chrono>
std::mt19937 engine(std::chrono::system_clock::now().time_since_epoch().count());



int main()
{
    welcome();
    enter();
    clear_screen();

    print_board();

    do
    {
        chooseGameMode();
        chooseNickname();
        play_game();
    } while (play_again());

    return 0;
}



/*
void mode3AIMove()
{
    for (int i = 0; i < 2; ++i)
    {
        if (gameBoard[i][0] == marker2)
    }
}
*/


// Run program: Ctrl + F5 or Debug > Start Without Debugging menu
// Debug program: F5 or Debug > Start Debugging menu

// Tips for Getting Started:
//   1. Use the Solution Explorer window to add/manage files
//   2. Use the Team Explorer window to connect to source control
//   3. Use the Output window to see build output and other messages
//   4. Use the Error List window to view errors
//   5. Go to Project > Add New Item to create new code files, or Project > Add Existing Item to add existing code files to the project
//   6. In the future, to open this project again, go to File > Open > Project and select the .sln file
